# Generated by Django 4.2.25 on 2025-11-06 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('damage_type', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('primary_damage_type', models.CharField(max_length=50)),
                ('primary_role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'champions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChampionPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'champion_patches',
                'ordering': ['patch', 'champion'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patches',
                'ordering': ['-date', '-version_num'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WinLossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_loss_records', to='league.champion')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_loss_records', to='league.season')),
            ],
            options={
                'db_table': 'win_loss_records',
                'ordering': ['season', '-wins', 'champion'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='league.patch')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tournaments', to='league.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tournaments', to='league.tournament')),
            ],
            options={
                'db_table': 'team_tournaments',
                'ordering': ['tournament', 'placement'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(related_name='teams', through='league.TeamTournament', to='league.tournament'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['date'], name='seasons_date_c884ea_idx'),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['date'], name='patches_date_d3507b_idx'),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['version_num'], name='patches_version_8a8ce1_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_games', to='league.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team_champion_pick_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_pick_1_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team_champion_pick_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_pick_2_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team_champion_pick_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_pick_3_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team_champion_pick_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_pick_4_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team_champion_pick_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_pick_5_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='bot_lane_winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_lane_wins', to='league.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='mid_lane_winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mid_lane_wins', to='league.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='patch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='league.patch'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_games', to='league.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team_champion_pick_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_pick_1_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team_champion_pick_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_pick_2_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team_champion_pick_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_pick_3_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team_champion_pick_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_pick_4_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team_champion_pick_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_pick_5_games', to='league.champion'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='league.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='top_lane_winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_lane_wins', to='league.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='league.tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='league.team'),
        ),
        migrations.AddField(
            model_name='championpatch',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_patches', to='league.champion'),
        ),
        migrations.AddField(
            model_name='championpatch',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_patches', to='league.patch'),
        ),
        migrations.AddIndex(
            model_name='winlossrecord',
            index=models.Index(fields=['champion', 'season'], name='win_loss_re_champio_608f15_idx'),
        ),
        migrations.AddIndex(
            model_name='winlossrecord',
            index=models.Index(fields=['season'], name='win_loss_re_season__4a517b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='winlossrecord',
            unique_together={('champion', 'season')},
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['date'], name='tournaments_date_634226_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['tier'], name='tournaments_tier_384c97_idx'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['team', 'tournament'], name='team_tourna_team_id_909cae_idx'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['tournament', 'placement'], name='team_tourna_tournam_cf44c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamtournament',
            unique_together={('team', 'tournament')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['region'], name='teams_region_652a69_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='games_date_02ed81_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['patch', 'date'], name='games_patch_i_737c74_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['tournament', 'date'], name='games_tournam_9778cf_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'date'], name='games_season__6ec7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['blue_team', 'date'], name='games_blue_te_52c731_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['red_team', 'date'], name='games_red_tea_67c4db_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['winning_team'], name='games_winning_182568_idx'),
        ),
        migrations.AddIndex(
            model_name='championpatch',
            index=models.Index(fields=['champion', 'patch'], name='champion_pa_champio_49a3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='championpatch',
            index=models.Index(fields=['patch'], name='champion_pa_patch_i_fcd383_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='championpatch',
            unique_together={('champion', 'patch')},
        ),
    ]
