# Generated by Django 4.2.25 on 2025-11-06 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='KDA',
            field=models.FloatField(default=0.0, help_text='Kill/Death/Assist ratio (float)'),
        ),
        migrations.AddField(
            model_name='champion',
            name='avg_bt',
            field=models.FloatField(default=0.0, help_text='Average Baron time (float, minutes)'),
        ),
        migrations.AddField(
            model_name='champion',
            name='avg_rp',
            field=models.FloatField(default=0.0, help_text='Average Rift time (float, minutes)'),
        ),
        migrations.AddField(
            model_name='champion',
            name='bans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='csd_15',
            field=models.IntegerField(default=0, help_text='CS difference at 15 minutes'),
        ),
        migrations.AddField(
            model_name='champion',
            name='csm',
            field=models.FloatField(default=0.0, help_text='Creep score per minute'),
        ),
        migrations.AddField(
            model_name='champion',
            name='dpm',
            field=models.PositiveIntegerField(default=0, help_text='Damage per minute'),
        ),
        migrations.AddField(
            model_name='champion',
            name='gd_15',
            field=models.IntegerField(default=0, help_text='Gold difference at 15 minutes'),
        ),
        migrations.AddField(
            model_name='champion',
            name='gpm',
            field=models.PositiveIntegerField(default=0, help_text='Gold per minute'),
        ),
        migrations.AddField(
            model_name='champion',
            name='gt',
            field=models.DurationField(blank=True, help_text='Average game time (duration)', null=True),
        ),
        migrations.AddField(
            model_name='champion',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='picks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='prioscore',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Priority score as a percent (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='champion',
            name='winrate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate as a percent (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='champion',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='xpd_15',
            field=models.IntegerField(default=0, help_text='XP difference at 15 minutes'),
        ),
    ]
