# Generated by Django 4.2.25 on 2025-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_champion_kda_champion_avg_bt_champion_avg_rp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='damage_type',
        ),
        migrations.AlterField(
            model_name='champion',
            name='primary_damage_type',
            field=models.CharField(help_text='Primary damage type: AD or AP (what the champion builds)', max_length=50),
        ),
    ]
