# Generated by Django 4.2.25 on 2025-11-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_remove_champion_damage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='champion',
            name='primary_role',
            field=models.CharField(blank=True, help_text="Deprecated: Use 'roles' instead. Kept for backwards compatibility.", max_length=50),
        ),
        migrations.AddField(
            model_name='champion',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Champion roles (can have multiple)', related_name='champions', to='league.role'),
        ),
    ]
