# Generated by Django 4.2.25 on 2025-11-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_role_alter_champion_primary_role_champion_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='primary_role',
        ),
    ]
