# Generated by Django 4.2.25 on 2025-11-06 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_remove_champion_primary_role'),
    ]

    operations = [
        # Update Django's state to use the existing join table.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations; the table already exists.
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='champion',
                    name='roles',
                    field=models.ManyToManyField(blank=True, db_table='champions_roles', help_text='Champion roles (can have multiple)', related_name='champions', to='league.role'),
                ),
            ],
        ),
    ]
