# Generated by Django 4.2.25 on 2025-11-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_championrole_alter_champion_roles'),
    ]

    operations = [
        # Use SeparateDatabaseAndState because the table already exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Don't create the table - it already exists
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ChampionRole',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('champion', models.ForeignKey(db_column='champion_id', on_delete=django.db.models.deletion.CASCADE, to='league.champion')),
                        ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='league.role')),
                    ],
                    options={
                        'db_table': 'champions_roles',
                        'unique_together': {('champion', 'role')},
                    },
                ),
                migrations.AlterField(
                    model_name='champion',
                    name='roles',
                    field=models.ManyToManyField(blank=True, help_text='Champion roles (can have multiple)', related_name='champions', through='league.ChampionRole', to='league.role'),
                ),
            ],
        ),
    ]
