# Generated by Django 4.2.25 on 2025-11-08 00:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_championrole_alter_champion_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picks', models.PositiveIntegerField(default=0)),
                ('bans', models.PositiveIntegerField(default=0)),
                ('prioscore', models.DecimalField(decimal_places=2, default=0.0, help_text='Priority score as a percent (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('winrate', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate as a percent (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('KDA', models.FloatField(default=0.0, help_text='Kill/Death/Assist ratio (float)')),
                ('avg_bt', models.FloatField(default=0.0, help_text='Average Baron time (float, minutes)')),
                ('avg_rp', models.FloatField(default=0.0, help_text='Average Rift time (float, minutes)')),
                ('gt', models.DurationField(blank=True, help_text='Average game time (duration)', null=True)),
                ('csm', models.FloatField(default=0.0, help_text='Creep score per minute')),
                ('dpm', models.PositiveIntegerField(default=0, help_text='Damage per minute')),
                ('gpm', models.PositiveIntegerField(default=0, help_text='Gold per minute')),
                ('csd_15', models.IntegerField(default=0, help_text='CS difference at 15 minutes')),
                ('gd_15', models.IntegerField(default=0, help_text='Gold difference at 15 minutes')),
                ('xpd_15', models.IntegerField(default=0, help_text='XP difference at 15 minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'champion_season_stats',
                'ordering': ['season', 'champion'],
            },
        ),
        migrations.RemoveField(
            model_name='champion',
            name='KDA',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='avg_bt',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='avg_rp',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='bans',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='csd_15',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='csm',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='dpm',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='gd_15',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='gpm',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='gt',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='picks',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='prioscore',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='winrate',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='xpd_15',
        ),
        migrations.DeleteModel(
            name='WinLossRecord',
        ),
        migrations.AddField(
            model_name='championseasonstats',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='league.champion'),
        ),
        migrations.AddField(
            model_name='championseasonstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_stats', to='league.season'),
        ),
        migrations.AddIndex(
            model_name='championseasonstats',
            index=models.Index(fields=['champion', 'season'], name='champion_se_champio_8e8f74_idx'),
        ),
        migrations.AddIndex(
            model_name='championseasonstats',
            index=models.Index(fields=['season'], name='champion_se_season__31eac3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='championseasonstats',
            unique_together={('champion', 'season')},
        ),
    ]
