# Generated by Django 4.2.25 on 2025-11-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_teamseasonstats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-last_game_date', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='season',
            name='seasons_date_c884ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='tournaments_date_634226_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE seasons DROP COLUMN IF EXISTS date;',
                    reverse_sql="ALTER TABLE seasons ADD COLUMN date date NULL;"
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='season',
                    name='date',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE tournaments DROP COLUMN IF EXISTS date;',
                    reverse_sql="ALTER TABLE tournaments ADD COLUMN date date NULL;"
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='tournament',
                    name='date',
                ),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='details_url',
            field=models.URLField(blank=True, help_text='Link to the tournament details page.', max_length=500),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last_game_date',
            field=models.DateField(blank=True, help_text='Date of the final game listed for the tournament.', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region',
            field=models.CharField(blank=True, help_text='Region code for the event (e.g., NA, EUW, KR).', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season_name',
            field=models.CharField(blank=True, help_text='Season identifier associated with the tournament (e.g., s15).', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tier',
            field=models.CharField(blank=True, help_text='Optional tier label (e.g., S-Tier, A-Tier)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['last_game_date'], name='tournaments_last_ga_399c27_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['region'], name='tournaments_region_067dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['season_name'], name='tournaments_season__54b67b_idx'),
        ),
    ]
