# Generated by Django 4.2.25 on 2025-11-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_href', models.CharField(blank=True, help_text='Relative href extracted from gol.gg.', max_length=500)),
                ('match_url', models.URLField(help_text='Canonical gol.gg URL for the match overview.', max_length=500, unique=True)),
                ('team_one_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_two_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week', models.CharField(blank=True, max_length=50)),
                ('patch', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_one', models.ForeignKey(help_text='Team listed in the first column (typically blue side).', on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_one', to='league.team')),
                ('team_two', models.ForeignKey(help_text='Team listed in the second column (typically red side).', on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_two', to='league.team')),
                ('tournament', models.ForeignKey(help_text='Tournament the match belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.tournament')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-date', 'tournament', 'team_one__name', 'team_two__name'],
                'indexes': [models.Index(fields=['date'], name='matches_date_c27a85_idx'), models.Index(fields=['tournament', 'date'], name='matches_tournam_28afe8_idx'), models.Index(fields=['team_one'], name='matches_team_on_398331_idx'), models.Index(fields=['team_two'], name='matches_team_tw_fb1ec4_idx')],
                'unique_together': {('tournament', 'match_url')},
            },
        ),
    ]
