# Generated by Django 4.2.25 on 2025-11-11 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_match'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_patch_i_737c74_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_tournam_9778cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_season__6ec7ec_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='league.match'),
        ),
    ]
