# Generated by Django 4.2.25 on 2025-11-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_alter_game_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.URLField(blank=True, help_text='Canonical gol.gg URL for the game overview.', max_length=500),
        ),
    ]
