# Generated by Django 4.2.25 on 2025-11-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_game_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ordinal number of the game within the match (1-indexed).'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['match', 'game_number'], name='games_match_i_dca1b4_idx'),
        ),
    ]
